name: Enviar correo de prueba

on:
  workflow_dispatch:

jobs:
  enviar:

    runs-on: ubuntu-latest

    env:
      FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
      GMAIL_USER: ${{ secrets.GMAIL_USER }}
      GMAIL_APP_PASSWORD: ${{ secrets.GMAIL_APP_PASSWORD }}

    steps:

      - name: Descargar proyecto
        uses: actions/checkout@v4

      - name: Instalar Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Instalar dependencias
        run: npm install

      - name: Ejecutar script
        run: node scripts/enviar-prueba.js
